### ISSUE TITLE
Use Netlify

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/zcashfoundation.github.io#12]
Justify this later - CDN, branched builds, etc

**Comment by RichardLitt** [comment]
We probably don't need branched builds, which means this probably isn't needed.

**Comment by sonyamann** [comment]
I'll leave this decision to you and @acityinohio.

**Comment by acityinohio** [comment]
I'd say skip for now as we can always migrate, particularly since GitHub now supports SSL without much headache for pages.

**Comment by RichardLitt** [comment]
Cool. Skipping! Will reopen if I find a specific need.
