### ISSUE TITLE
Sync to current logo and branding guidelines

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/zcashfoundation.github.io#17]
See Google Drive and PDF.

**Comment by RichardLitt** [comment]
The Filson Pro family [costs money](https://www.fonts.com/font/mostardesign-studio/filson-pro?QueryFontType=Web&src=GoogleWebFonts). Want me to buy these and then invoice for them? 

Note to myself: currently loading fonts over Google Fonts, might want to use local files.

**Comment by sonyamann** [comment]
Yeah, please purchase and invoice. Antonie can reimburse you.

Re: your note to self, my limited knowledge of making websites fast is that fancy fonts are a frequent slowdown culprit. I assume we can mitigate that by falling back on system fonts when necessary and generally delivering the font files in whatever way you have planned?

**Comment by RichardLitt** [comment]
Purchased. I'm unable to download them - tried on three different browsers, then contacted support - and will update this as soon as I am able. 

Exactly. That note was just a reminder to check if I should use the asset files or the Google Fonts api for serving them. I'm going with the latter.

**Comment by RichardLitt** [comment]
I believe that this should be done for now.
