### ISSUE TITLE
Rework site map

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/zcashfoundation.github.io#2]
From Sonya: We should rework the homepage structure like so.

Homepage

—> About

  ——> Mission + values

  ——> Team

  ——> Legal info

  ——> Contact page

—> Blog

—> Resources

  ——> page(s) of curated links

  ——> block explorer (out of scope for this project but will be added eventually)

—> Governance

  ——> Elections

    —> 2018

    —> 2017

  ——> Community Advisory Panel

—> Grants

  ——> About

  ——> 2018

  ——> 2017

—> Community

  ——> list of existing meetups + guide to hosting your own
  ——> link to Zcash Community main website
  ——> chat.zcashcommunity.com
  ——> Forum (currently forum.z.cash but will be handed over to the Foundation soonish)

  ——> link to /r/zec?

**Comment by RichardLitt** [comment]
Done pending feedback.

**Comment by sonyamann** [comment]
I'm happy with what you set up. I'll poke around more and let you know if I think anything should be moved or changed.

**Comment by RichardLitt** [comment]
Sounds good! Reopen as needed.
