### ISSUE TITLE
Logo adjustments

### ISSUE THREAD

**Issue by sonyamann** [RichardLitt/zcashfoundation.github.io#23]
When you open the website, the header logo and navbar do a little loading animation. Let's get rid of that, it's annoying.

And then let's switch to using this logo: https://drive.google.com/file/d/0B17UGNtR0dOJcVFldmxMdHFOZG5IMzlVM0ZMVmJJQXRVUjk4/view?usp=sharing

And remove the header text that says "The Zcash Foundation" — that can be the logo image alt text instead, perhaps?

**Comment by sonyamann** [comment]
Lmk if any of the above is unclear.

**Comment by RichardLitt** [comment]
All clear. Had already done the last point; changed the other two now.
