### ISSUE TITLE
Add items to homepage

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/zcashfoundation.github.io#3]
Things that should go on the homepage: A snippet of "here's who we are and what we do," a newsletter signup prompt, promotion of our current focus (e.g. an upcoming conference), and pointers to the most commonly used resources.

**Comment by RichardLitt** [comment]
In progress, but needs feedback.

**Comment by sonyamann** [comment]
Assign this one to me? I'll get you some copy. Not sure exactly when but I should have time to work on it next week.

**Comment by RichardLitt** [comment]
Added you as contributor, so that I can assign you. No rush!

**Comment by RichardLitt** [comment]
@sonyamann Any word on the copy here?

**Comment by sonyamann** [comment]
Still workin' on it. How about making the deadline Tuesday? (I work better with deadlines.)

**Comment by RichardLitt** [comment]
Works for me. :)

**Comment by sonyamann** [comment]
```
The Zcash Foundation is a financial privacy nonprofit. [Our mission](mission) is to build and support the technology infrastructure that will enable people to control their own financial data. The protocol [Zcash](meetups/Zcash%20onepager%20color.pdf), with its landmark use of zero-knowledge cryptography, is the most promising long-term approach.

## Newsletter

Subscribe to receive announcements and program updates from the Zcash Foundation.

<form
  action="https://buttondown.email/api/emails/embed-subscribe/zcashfoundation"
  method="post"
  target="popupwindow"
  onsubmit="window.open('https://buttondown.email/zcashfoundation', 'popupwindow')"
  class="embeddable-buttondown-form"
>
  <label for="bd-email">Enter your email:</label>
  <input type="email" name="email" id="bd-email">
  <input type="hidden" value="1" name="embed"/>
  <input type="submit" value="Subscribe now!" />
</form>
```

For these sections — "promotion of our current focus (e.g. an upcoming conference), and pointers to the most commonly used resources." — I basically want buckets that I can put content in when it's ready. Does that make sense?

**Comment by RichardLitt** [comment]
Yep! I'll just use lorem ipsem for now.

**Comment by sonyamann** [comment]
Aside from the lorem ipsum buckets, this is the up-to-date homepage language: https://github.com/ZcashFoundation/zcashfoundation.github.io/blob/master/index.html

**Comment by RichardLitt** [comment]
Pretty sure this is done as of now! :)
