### ISSUE TITLE
Add contact form partial

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/zcashfoundation.github.io#4]
Should be on various pages.

**Comment by RichardLitt** [comment]
Need details for what should be on this form.

**Comment by sonyamann** [comment]
Contact the Zcash Foundation:

[mandatory subject line field labeled "Subject"]

[mandatory body field labeled "Content"]

[mandatory email field labeled "Email address"]

[button labeled "Submit"]

You can also get in touch by emailing contact@[new URL].

-----

Thanks! We have received your message and will reply shortly.

**Comment by RichardLitt** [comment]
I'm not sure that we need to have an email form, here. Forms on Jekyll are impossible to do without having a third party service set up, which can cost money, time, and security concerns (the third party can then access the email accounts, too). 

Could we just add the contact@newurl address, instead?

**Comment by sonyamann** [comment]
Yeah that works. A contact form would be slightly better but tradeoffs, always tradeoffs!

I'm not sure if this is feasible, but it'd be ideal to have some kind of reusable box where we could update the language once and it'd propagate to every place on the site with a contact CTA

**Comment by RichardLitt** [comment]
> I'm not sure if this is feasible, but it'd be ideal to have some kind of reusable box where we could update the language once and it'd propagate to every place on the site with a contact CTA

This is very doable. Will do before I close this.

**Comment by RichardLitt** [comment]
Where did you imagine that the Contact CTA would go? Right now, all I can imagine for this is:

> If you have any questions, please email [contact@z.cash.foundation](mailto:contact@z.cash.foundation).

Which only exists on the grants and the about page, at the moment.

**Comment by sonyamann** [comment]
I'm thinking like

[page content]
[contact CTA, automatically added to every page or post on the website]
[footer + legal disclaimer]

Does that make sense? And yes, that text is fine.

**Comment by RichardLitt** [comment]
I'm not quite sure it works with the design. I've added it to the footer; how does this look? 

<img width="1011" alt="screen shot 2018-11-15 at 11 57 53" src="https://user-images.githubusercontent.com/910753/48568578-ba84b880-e8cd-11e8-806c-a8e38f0e7c27.png">

**Comment by sonyamann** [comment]
Yeah that works for me!

**Comment by RichardLitt** [comment]
Great! Calling this closed then.
