### ISSUE TITLE
Add license and terms to footer

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/zcashfoundation.github.io#9]

**Comment by RichardLitt** [comment]
These are in the footer. There's no Terms and Conditions, though.

**Comment by sonyamann** [comment]
Looping in Josh and Antonie via email. (You are CC'd.) I will cross-post whatever we decide here.

**Comment by RichardLitt** [comment]
@sonyamann Any word on this?

**Comment by sonyamann** [comment]
For now: `© 2018 Zcash Foundation`

I don't think our main website needs a ToS since all that people can do is look at it, but we'll use the docs from the forum as needed in the future.

**Comment by sonyamann** [comment]
Can we have this image at the very bottom of the footer? Or maybe right above the copyright notice? https://drive.google.com/drive/folders/1Evf181Tx6SRDIDIZl4WMO3-c2tnqGqMr

**Comment by RichardLitt** [comment]
Which image? :)

**Comment by sonyamann** [comment]
Ahh, sorry. This link should go to the specific image: https://drive.google.com/file/d/0B17UGNtR0dOJaE5PYkNQT0kzQUsteWVReVJSNEJRMFF5cXVN/view?usp=sharing

(just tested it in an incognito window)
